
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 7.1.2 EDK_H.12.5.1
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xuartlite.h"

/*
* The configuration table for devices
*/

XUartLite_Config XUartLite_ConfigTable[] =
{
	{
		XPAR_RS232_UART_1_DEVICE_ID,
		XPAR_RS232_UART_1_BASEADDR,
		XPAR_RS232_UART_1_BAUDRATE,
		XPAR_RS232_UART_1_USE_PARITY,
		XPAR_RS232_UART_1_ODD_PARITY,
		XPAR_RS232_UART_1_DATA_BITS
	}
};


