#################################################################
# Makefile generated by Xilinx Platform Studio 
# Project:F:\fpga\proj\DesignContest08_vjs_64bit_blk4\system.xmp
#################################################################

XILINX_EDK_DIR = C:/EDK

SYSTEM = system

MHSFILE = system.mhs

MSSFILE = system.mss

FPGA_ARCH = virtex2p

DEVICE = xc2vp30ff896-7

LANGUAGE = vhdl

SEARCHPATHOPT = 

SUBMODULE_OPT = 

PLATGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(SUBMODULE_OPT)

LIBGEN_OPTIONS = -mhs $(MHSFILE) -p $(DEVICE) $(SEARCHPATHOPT)

VPGEN_OPTIONS = -p $(DEVICE) $(SEARCHPATHOPT)

TESTAPP_MEMORY_OUTPUT_DIR = TestApp_Memory
TESTAPP_MEMORY_OUTPUT = $(TESTAPP_MEMORY_OUTPUT_DIR)/executable.elf

TESTAPP_PERIPHERAL_OUTPUT_DIR = TestApp_Peripheral
TESTAPP_PERIPHERAL_OUTPUT = $(TESTAPP_PERIPHERAL_OUTPUT_DIR)/executable.elf

MERGE_SORT64_OUTPUT_DIR = merge_sort64
MERGE_SORT64_OUTPUT = $(MERGE_SORT64_OUTPUT_DIR)/executable.elf

METRIC_OUTPUT_DIR = metric
METRIC_OUTPUT = $(METRIC_OUTPUT_DIR)/executable.elf

MICROBLAZE_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop.elf
PPC405_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc405/ppc_bootloop.elf
BOOTLOOP_DIR = bootloops

PPC405_0_BOOTLOOP = $(BOOTLOOP_DIR)/ppc405_0.elf

PPC405_1_BOOTLOOP = $(BOOTLOOP_DIR)/ppc405_1.elf

BRAMINIT_ELF_FILES =   $(PPC405_0_BOOTLOOP) 
BRAMINIT_ELF_FILE_ARGS =   -pe ppc405_0  $(PPC405_0_BOOTLOOP) 

ALL_USER_ELF_FILES = $(TESTAPP_MEMORY_OUTPUT) $(TESTAPP_PERIPHERAL_OUTPUT) $(MERGE_SORT64_OUTPUT) $(METRIC_OUTPUT) 

SIM_CMD = vsim

BEHAVIORAL_SIM_SCRIPT = simulation/behavioral/$(SYSTEM).do

STRUCTURAL_SIM_SCRIPT = simulation/structural/$(SYSTEM).do

TIMING_SIM_SCRIPT = simulation/timing/$(SYSTEM).do

DEFAULT_SIM_SCRIPT = $(BEHAVIORAL_SIM_SCRIPT)

MIX_LANG_SIM_OPT = -mixed yes

SIMGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(SUBMODULE_OPT) $(BRAMINIT_ELF_FILE_ARGS) $(MIX_LANG_SIM_OPT)  -s mti


LIBRARIES =  \
       ppc405_0/lib/libxil.a  \
       ppc405_1/lib/libxil.a 
VPEXEC = virtualplatform/vpexec.exe

LIBSCLEAN_TARGETS = ppc405_0_libsclean ppc405_1_libsclean 

PROGRAMCLEAN_TARGETS = TestApp_Memory_programclean TestApp_Peripheral_programclean merge_sort64_programclean metric_programclean 

CORE_STATE_DEVELOPMENT_FILES = C:\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v1_00_b\hdl\vhdl\proc_common_pkg.vhd \
C:\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v1_00_b\hdl\vhdl\family.vhd \
C:\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v1_00_b\hdl\vhdl\or_muxcy.vhd \
C:\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v1_00_b\hdl\vhdl\or_gate.vhd \
C:\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v1_00_b\hdl\vhdl\pselect.vhd \
C:\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v1_00_b\hdl\vhdl\inferred_lut4.vhd \
C:\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v1_00_b\hdl\vhdl\srl_fifo2.vhd \
C:\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v1_00_b\hdl\vhdl\counter_bit.vhd \
C:\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v1_00_b\hdl\vhdl\counter.vhd \
C:\EDK\hw\XilinxProcessorIPLib\pcores\ipif_common_v1_00_b\hdl\vhdl\ipif_pkg.vhd \
C:\EDK\hw\XilinxProcessorIPLib\pcores\ipif_common_v1_00_b\hdl\vhdl\ipif_steer.vhd \
C:\EDK\hw\XilinxProcessorIPLib\pcores\plb_ipif_v1_00_e\hdl\vhdl\pf_counter_bit.vhd \
C:\EDK\hw\XilinxProcessorIPLib\pcores\plb_ipif_v1_00_e\hdl\vhdl\pf_counter.vhd \
C:\EDK\hw\XilinxProcessorIPLib\pcores\plb_ipif_v1_00_e\hdl\vhdl\pf_counter_top.vhd \
C:\EDK\hw\XilinxProcessorIPLib\pcores\plb_ipif_v1_00_e\hdl\vhdl\pf_occ_counter.vhd \
C:\EDK\hw\XilinxProcessorIPLib\pcores\plb_ipif_v1_00_e\hdl\vhdl\pf_occ_counter_top.vhd \
C:\EDK\hw\XilinxProcessorIPLib\pcores\plb_ipif_v1_00_e\hdl\vhdl\pf_adder_bit.vhd \
C:\EDK\hw\XilinxProcessorIPLib\pcores\plb_ipif_v1_00_e\hdl\vhdl\pf_adder.vhd \
C:\EDK\hw\XilinxProcessorIPLib\pcores\plb_ipif_v1_00_e\hdl\vhdl\pf_dpram_select.vhd \
C:\EDK\hw\XilinxProcessorIPLib\pcores\plb_ipif_v1_00_e\hdl\vhdl\srl16_fifo.vhd \
C:\EDK\hw\XilinxProcessorIPLib\pcores\plb_ipif_v1_00_e\hdl\vhdl\pf_dly1_mux.vhd \
C:\EDK\hw\XilinxProcessorIPLib\pcores\plb_ipif_v1_00_e\hdl\vhdl\rdpfifo_dp_cntl.vhd \
C:\EDK\hw\XilinxProcessorIPLib\pcores\plb_ipif_v1_00_e\hdl\vhdl\ipif_control_rd.vhd \
C:\EDK\hw\XilinxProcessorIPLib\pcores\plb_ipif_v1_00_e\hdl\vhdl\rdpfifo_top.vhd \
C:\EDK\hw\XilinxProcessorIPLib\pcores\plb_ipif_v1_00_e\hdl\vhdl\wrpfifo_dp_cntl.vhd \
C:\EDK\hw\XilinxProcessorIPLib\pcores\plb_ipif_v1_00_e\hdl\vhdl\ipif_control_wr.vhd \
C:\EDK\hw\XilinxProcessorIPLib\pcores\plb_ipif_v1_00_e\hdl\vhdl\wrpfifo_top.vhd \
C:\EDK\hw\XilinxProcessorIPLib\pcores\plb_ipif_v1_00_e\hdl\vhdl\flex_addr_cntr.vhd \
C:\EDK\hw\XilinxProcessorIPLib\pcores\plb_ipif_v1_00_e\hdl\vhdl\addr_reg_cntr_brst_flex.vhd \
C:\EDK\hw\XilinxProcessorIPLib\pcores\plb_ipif_v1_00_e\hdl\vhdl\plb_address_decoder.vhd \
C:\EDK\hw\XilinxProcessorIPLib\pcores\plb_ipif_v1_00_e\hdl\vhdl\burst_support.vhd \
C:\EDK\hw\XilinxProcessorIPLib\pcores\plb_ipif_v1_00_e\hdl\vhdl\plb_slave_attachment_indet.vhd \
C:\EDK\hw\XilinxProcessorIPLib\pcores\plb_ipif_v1_00_e\hdl\vhdl\plb_sesr_sear.vhd \
C:\EDK\hw\XilinxProcessorIPLib\pcores\plb_ipif_v1_00_e\hdl\vhdl\plb_ipif_reset.vhd \
C:\EDK\hw\XilinxProcessorIPLib\pcores\plb_ipif_v1_00_e\hdl\vhdl\plb_interrupt_control.vhd \
C:\EDK\hw\XilinxProcessorIPLib\pcores\plb_ipif_v1_00_e\hdl\vhdl\plb_ipif.vhd \
F:\fpga\proj\DesignContest08_vjs_64bit_blk4\pcores\accel_sort_plb_v1_00_a\hdl\verilog\accel_sort.v \
F:\fpga\proj\DesignContest08_vjs_64bit_blk4\pcores\accel_sort_plb_v1_00_a\hdl\verilog\aes_cipher_top.v \
F:\fpga\proj\DesignContest08_vjs_64bit_blk4\pcores\accel_sort_plb_v1_00_a\hdl\verilog\aes_key_expand_128.v \
F:\fpga\proj\DesignContest08_vjs_64bit_blk4\pcores\accel_sort_plb_v1_00_a\hdl\verilog\aes_keygen.v \
F:\fpga\proj\DesignContest08_vjs_64bit_blk4\pcores\accel_sort_plb_v1_00_a\hdl\verilog\aes_rcon.v \
F:\fpga\proj\DesignContest08_vjs_64bit_blk4\pcores\accel_sort_plb_v1_00_a\hdl\verilog\aes_sbox.v \
F:\fpga\proj\DesignContest08_vjs_64bit_blk4\pcores\accel_sort_plb_v1_00_a\hdl\verilog\fifo_rd_64_to_128.v \
F:\fpga\proj\DesignContest08_vjs_64bit_blk4\pcores\accel_sort_plb_v1_00_a\hdl\verilog\fifo_wr_128_to_64.v \
F:\fpga\proj\DesignContest08_vjs_64bit_blk4\pcores\accel_sort_plb_v1_00_a\hdl\verilog\user_logic.v \
F:\fpga\proj\DesignContest08_vjs_64bit_blk4\pcores\accel_sort_plb_v1_00_a\hdl\vhdl\accel_sort_plb.vhd

WRAPPER_NGC_FILES = implementation/ppc405_0_wrapper.ngc \
implementation/ppc405_1_wrapper.ngc \
implementation/jtagppc_0_wrapper.ngc \
implementation/reset_block_wrapper.ngc \
implementation/iocm_wrapper.ngc \
implementation/iocm_cntlr_wrapper.ngc \
implementation/isocm_bram_wrapper.ngc \
implementation/plb_wrapper.ngc \
implementation/opb_wrapper.ngc \
implementation/plb2opb_wrapper.ngc \
implementation/rs232_uart_1_wrapper.ngc \
implementation/ddr_512mb_64mx64_rank2_row13_col10_cl2_5_wrapper.ngc \
implementation/sysclk_inv_wrapper.ngc \
implementation/clk90_inv_wrapper.ngc \
implementation/ddr_clk90_inv_wrapper.ngc \
implementation/dcm_0_wrapper.ngc \
implementation/dcm_1_wrapper.ngc \
implementation/accel_sort_plb_0_wrapper.ngc

POSTSYN_NETLIST = implementation/$(SYSTEM).ngc

SYSTEM_BIT = implementation/$(SYSTEM).bit

DOWNLOAD_BIT = implementation/download.bit

SYSTEM_ACE = implementation/$(SYSTEM).ace

UCF_FILE = data/system.ucf

BMM_FILE = implementation/$(SYSTEM).bmm

FASTRUNTIME_OPT_FILE = etc/fast_runtime.opt
BITGEN_UT_FILE = etc/bitgen.ut

#################################################################
# SOFTWARE APPLICATION TESTAPP_MEMORY
#################################################################

TESTAPP_MEMORY_SOURCES = TestApp_Memory/src/TestApp_Memory.c 

TESTAPP_MEMORY_HEADERS = 

TESTAPP_MEMORY_CC = powerpc-eabi-gcc
TESTAPP_MEMORY_CC_SIZE = powerpc-eabi-size
TESTAPP_MEMORY_CC_OPT = -O2
TESTAPP_MEMORY_CFLAGS = 
TESTAPP_MEMORY_CC_SEARCH = # -B
TESTAPP_MEMORY_LIBPATH = -L./ppc405_0/lib/ # -L
TESTAPP_MEMORY_INCLUDES = -I./ppc405_0/include/ # -I
TESTAPP_MEMORY_LFLAGS = # -l
TESTAPP_MEMORY_CC_PREPROC_FLAG = # -Wp,
TESTAPP_MEMORY_CC_ASM_FLAG = # -Wa,
TESTAPP_MEMORY_CC_LINKER_FLAG = # -Wl,
TESTAPP_MEMORY_LINKER_SCRIPT = TestApp_Memory/src/TestApp_Memory_LinkScr
TESTAPP_MEMORY_LINKER_SCRIPT_FLAG = -Wl,-T -Wl,$(TESTAPP_MEMORY_LINKER_SCRIPT) 
TESTAPP_MEMORY_CC_DEBUG_FLAG =  -g 
TESTAPP_MEMORY_CC_GLOBPTR_FLAG= # -msdata=eabi
TESTAPP_MEMORY_CC_START_ADDR_FLAG=  # -Wl,-defsym -Wl,_START_ADDR=
TESTAPP_MEMORY_CC_STACK_SIZE_FLAG=  # -Wl,-defsym -Wl,_STACK_SIZE=
TESTAPP_MEMORY_CC_HEAP_SIZE_FLAG=  # -Wl,-defsym -Wl,_HEAP_SIZE=
TESTAPP_MEMORY_OTHER_CC_FLAGS= $(TESTAPP_MEMORY_CC_GLOBPTR_FLAG)  \
                  $(TESTAPP_MEMORY_CC_START_ADDR_FLAG) $(TESTAPP_MEMORY_CC_STACK_SIZE_FLAG) $(TESTAPP_MEMORY_CC_HEAP_SIZE_FLAG)  \
                  $(TESTAPP_MEMORY_CC_PREPROC_FLAG) $(TESTAPP_MEMORY_CC_ASM_FLAG) $(TESTAPP_MEMORY_CC_LINKER_FLAG)  \
                  $(TESTAPP_MEMORY_LINKER_SCRIPT_FLAG) $(TESTAPP_MEMORY_CC_DEBUG_FLAG) 

#################################################################
# SOFTWARE APPLICATION TESTAPP_PERIPHERAL
#################################################################

TESTAPP_PERIPHERAL_SOURCES = TestApp_Peripheral/src/TestApp_Peripheral.c drivers/accel_sort_plb_v1_00_a/src/accel_sort_plb.c drivers/accel_sort_plb_v1_00_a/src/accel_sort_plb_selftest.c 

TESTAPP_PERIPHERAL_HEADERS = drivers/accel_sort_plb_v1_00_a/src/accel_sort_plb.h 

TESTAPP_PERIPHERAL_CC = powerpc-eabi-gcc
TESTAPP_PERIPHERAL_CC_SIZE = powerpc-eabi-size
TESTAPP_PERIPHERAL_CC_OPT = -O2
TESTAPP_PERIPHERAL_CFLAGS = 
TESTAPP_PERIPHERAL_CC_SEARCH = # -B
TESTAPP_PERIPHERAL_LIBPATH = -L./ppc405_0/lib/ # -L
TESTAPP_PERIPHERAL_INCLUDES = -I./ppc405_0/include/  -Idrivers/accel_sort_plb_v1_00_a/src/ # -I
TESTAPP_PERIPHERAL_LFLAGS = # -l
TESTAPP_PERIPHERAL_CC_PREPROC_FLAG = # -Wp,
TESTAPP_PERIPHERAL_CC_ASM_FLAG = # -Wa,
TESTAPP_PERIPHERAL_CC_LINKER_FLAG = # -Wl,
TESTAPP_PERIPHERAL_LINKER_SCRIPT = TestApp_Peripheral/src/TestApp_Peripheral_LinkScr
TESTAPP_PERIPHERAL_LINKER_SCRIPT_FLAG = -Wl,-T -Wl,$(TESTAPP_PERIPHERAL_LINKER_SCRIPT) 
TESTAPP_PERIPHERAL_CC_DEBUG_FLAG =  -g 
TESTAPP_PERIPHERAL_CC_GLOBPTR_FLAG= # -msdata=eabi
TESTAPP_PERIPHERAL_CC_START_ADDR_FLAG=  # -Wl,-defsym -Wl,_START_ADDR=
TESTAPP_PERIPHERAL_CC_STACK_SIZE_FLAG=  # -Wl,-defsym -Wl,_STACK_SIZE=
TESTAPP_PERIPHERAL_CC_HEAP_SIZE_FLAG=  # -Wl,-defsym -Wl,_HEAP_SIZE=
TESTAPP_PERIPHERAL_OTHER_CC_FLAGS= $(TESTAPP_PERIPHERAL_CC_GLOBPTR_FLAG)  \
                  $(TESTAPP_PERIPHERAL_CC_START_ADDR_FLAG) $(TESTAPP_PERIPHERAL_CC_STACK_SIZE_FLAG) $(TESTAPP_PERIPHERAL_CC_HEAP_SIZE_FLAG)  \
                  $(TESTAPP_PERIPHERAL_CC_PREPROC_FLAG) $(TESTAPP_PERIPHERAL_CC_ASM_FLAG) $(TESTAPP_PERIPHERAL_CC_LINKER_FLAG)  \
                  $(TESTAPP_PERIPHERAL_LINKER_SCRIPT_FLAG) $(TESTAPP_PERIPHERAL_CC_DEBUG_FLAG) 

#################################################################
# SOFTWARE APPLICATION MERGE_SORT64
#################################################################

MERGE_SORT64_SOURCES = merge_sort64/aes_core.c merge_sort64/main.c merge_sort64/msort.c merge_sort64/sortrecord_hw_plb.c drivers/accel_sort_plb_v1_00_a/src/accel_sort_plb.c drivers/accel_sort_plb_v1_00_a/src/accel_sort_util.c merge_sort64/recordio_tc.c 

MERGE_SORT64_HEADERS = merge_sort64/aes_core.h merge_sort64/msort.h merge_sort64/sortrecord_hw_plb.h merge_sort64/timer.h drivers/accel_sort_plb_v1_00_a/src/accel_sort_plb.h drivers/accel_sort_plb_v1_00_a/src/accel_sort_util.h merge_sort64/recordio_tc.h 

MERGE_SORT64_CC = powerpc-eabi-gcc
MERGE_SORT64_CC_SIZE = powerpc-eabi-size
MERGE_SORT64_CC_OPT = -O2
MERGE_SORT64_CFLAGS = 
MERGE_SORT64_CC_SEARCH = # -B
MERGE_SORT64_LIBPATH = -L./ppc405_0/lib/ # -L
MERGE_SORT64_INCLUDES = -I./ppc405_0/include/  -Imerge_sort64/ -Idrivers/accel_sort_plb_v1_00_a/src/ # -I
MERGE_SORT64_LFLAGS = # -l
MERGE_SORT64_CC_PREPROC_FLAG = # -Wp,
MERGE_SORT64_CC_ASM_FLAG = # -Wa,
MERGE_SORT64_CC_LINKER_FLAG = # -Wl,
MERGE_SORT64_LINKER_SCRIPT = merge_sort64_linker_script
MERGE_SORT64_LINKER_SCRIPT_FLAG = -Wl,-T -Wl,$(MERGE_SORT64_LINKER_SCRIPT) 
MERGE_SORT64_CC_DEBUG_FLAG =  -g 
MERGE_SORT64_CC_GLOBPTR_FLAG= # -msdata=eabi
MERGE_SORT64_CC_START_ADDR_FLAG=  # -Wl,-defsym -Wl,_START_ADDR=
MERGE_SORT64_CC_STACK_SIZE_FLAG=  # -Wl,-defsym -Wl,_STACK_SIZE=
MERGE_SORT64_CC_HEAP_SIZE_FLAG=  # -Wl,-defsym -Wl,_HEAP_SIZE=
MERGE_SORT64_OTHER_CC_FLAGS= $(MERGE_SORT64_CC_GLOBPTR_FLAG)  \
                  $(MERGE_SORT64_CC_START_ADDR_FLAG) $(MERGE_SORT64_CC_STACK_SIZE_FLAG) $(MERGE_SORT64_CC_HEAP_SIZE_FLAG)  \
                  $(MERGE_SORT64_CC_PREPROC_FLAG) $(MERGE_SORT64_CC_ASM_FLAG) $(MERGE_SORT64_CC_LINKER_FLAG)  \
                  $(MERGE_SORT64_LINKER_SCRIPT_FLAG) $(MERGE_SORT64_CC_DEBUG_FLAG) 

#################################################################
# SOFTWARE APPLICATION METRIC
#################################################################

METRIC_SOURCES = metric/aes_core.c metric/main_tc.c metric/recordio_tc.c metric/msort.c metric/sortrecord_hw_plb.c drivers/accel_sort_plb_v1_00_a/src/accel_sort_plb.c drivers/accel_sort_plb_v1_00_a/src/accel_sort_util.c 

METRIC_HEADERS = metric/aes_core.h metric/recordio_tc.h metric/timer.h metric/sortrecord_hw_plb.h metric/msort.h drivers/accel_sort_plb_v1_00_a/src/accel_sort_plb.h drivers/accel_sort_plb_v1_00_a/src/accel_sort_util.h 

METRIC_CC = powerpc-eabi-gcc
METRIC_CC_SIZE = powerpc-eabi-size
METRIC_CC_OPT = -O3
METRIC_CFLAGS = 
METRIC_CC_SEARCH = # -B
METRIC_LIBPATH = -L./ppc405_0/lib/ # -L
METRIC_INCLUDES = -I./ppc405_0/include/  -Imetric/ -Idrivers/accel_sort_plb_v1_00_a/src/ # -I
METRIC_LFLAGS = # -l
METRIC_CC_PREPROC_FLAG = # -Wp,
METRIC_CC_ASM_FLAG = # -Wa,
METRIC_CC_LINKER_FLAG = # -Wl,
METRIC_LINKER_SCRIPT = metric_linker_script
METRIC_LINKER_SCRIPT_FLAG = -Wl,-T -Wl,$(METRIC_LINKER_SCRIPT) 
METRIC_CC_DEBUG_FLAG = # -[g|gstabs]
METRIC_CC_GLOBPTR_FLAG= -msdata=eabi
METRIC_CC_START_ADDR_FLAG=  # -Wl,-defsym -Wl,_START_ADDR=
METRIC_CC_STACK_SIZE_FLAG=  # -Wl,-defsym -Wl,_STACK_SIZE=
METRIC_CC_HEAP_SIZE_FLAG=  # -Wl,-defsym -Wl,_HEAP_SIZE=
METRIC_OTHER_CC_FLAGS= $(METRIC_CC_GLOBPTR_FLAG)  \
                  $(METRIC_CC_START_ADDR_FLAG) $(METRIC_CC_STACK_SIZE_FLAG) $(METRIC_CC_HEAP_SIZE_FLAG)  \
                  $(METRIC_CC_PREPROC_FLAG) $(METRIC_CC_ASM_FLAG) $(METRIC_CC_LINKER_FLAG)  \
                  $(METRIC_LINKER_SCRIPT_FLAG) $(METRIC_CC_DEBUG_FLAG) 
